package models;
// Generated on the Mar 4, 2011 3:02:13 PM by Play!

import play.db.jpa.JPASupport;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Screencast generated by Play!
 */
@Entity
@Table(name="follower_log"
    , uniqueConstraints = {  }
)
public class FollowerLog extends JPASupport implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="id", unique=true, nullable=false, insertable=true, updatable=true)
        public int id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="user_id", unique=false, nullable=false, insertable=true, updatable=true)
        public User user;
    
    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "follower_id", nullable = false)
        public User follower;
    
    @Column(name="created_at", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date createdAt;
     // Constructors

    /** default constructor */
    public FollowerLog() {
    }

    /** full constructor */
    public FollowerLog(int id, User user, User follower, Date createdAt) {
       this.id = id;
       this.user = user;
       this.follower = follower;
       this.createdAt = createdAt;
    }
   


}


