package models;
// Generated on the Mar 4, 2011 3:49:12 PM by Play!

import play.db.jpa.JPASupport;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ScreencastComment generated by Play!
 */
@Entity
@Table(name="screencast_comment"
    , uniqueConstraints = {  }
)
public class ScreencastComment extends JPASupport implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="id", unique=true, nullable=false, insertable=true, updatable=true)
        public int id;
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="user_id", unique=false, nullable=false, insertable=true, updatable=true)
        public User user;
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="screencast_id", unique=false, nullable=false, insertable=true, updatable=true)
        public Screencast screencast;
    
    @Column(name="comments", unique=false, nullable=false, insertable=true, updatable=true, length=65535)
        public String comments;
    
    @Column(name="created_at", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date createdAt;
     // Constructors

    /** default constructor */
    public ScreencastComment() {
    }

    /** full constructor */
    public ScreencastComment(int id, User user, Screencast screencast, String comments, Date createdAt) {
       this.id = id;
       this.user = user;
       this.screencast = screencast;
       this.comments = comments;
       this.createdAt = createdAt;
    }
   


}


