package models;
// Generated on the Mar 4, 2011 3:34:41 PM by Play!

import play.db.jpa.JPASupport;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ScreencastViewLog generated by Play!
 */
@Entity
@Table(name="screencast_view_log"
    , uniqueConstraints = {  }
)
public class ScreencastViewLog extends JPASupport implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="id", unique=true, nullable=false, insertable=true, updatable=true)
        public int id;
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="user_id", unique=false, nullable=false, insertable=true, updatable=true)
        public User user;
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="screencast_id", unique=false, nullable=false, insertable=true, updatable=true)
        public Screencast screencast;
    
    @Column(name="created_at", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date createdAt;
     // Constructors

    /** default constructor */
    public ScreencastViewLog() {
    }

    /** full constructor */
    public ScreencastViewLog(int id, User user, Screencast screencast, Date createdAt) {
       this.id = id;
       this.user = user;
       this.screencast = screencast;
       this.createdAt = createdAt;
    }
   


}


